/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xYHqD5MkVkT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import React from "react";
import { ModeToggle } from "@/components/theme-picker";
import { DesktopIcon } from "@radix-ui/react-icons";

export function Navbar() {
    return (
        <nav className="shadow-sm">
            <div className="w-full px-4">
                <div className="flex justify-between h-14 items-center font-semibold">
                    <nav className="flex gap-4">
                        <Link
                            href="#"
                            className="flex items-center px-4"
                            prefetch={false}
                        >
                            <DesktopIcon className="h-[1.2rem] w-[1.2rem] transition-all"/>
                            <span className="sr-only">Acme Inc</span>
                        </Link>
                        <div className="hidden md:flex gap-4">
                            <Link
                                href="#"
                                className="flex items-center text-sm transition-colors hover:underline"
                                prefetch={false}
                            >
                                Home
                            </Link>
                            <Link
                                href="#"
                                className="flex items-center text-sm transition-colors hover:underline"
                                prefetch={false}
                            >
                                About
                            </Link>
                            <Link
                                href="#"
                                className="flex items-center text-sm transition-colors hover:underline"
                                prefetch={false}
                            >
                                Services
                            </Link>
                            <Link
                                href="#"
                                className="flex items-center text-sm transition-colors hover:underline"
                                prefetch={false}
                            >
                                Contact
                            </Link>
                        </div>
                    </nav>
                    <div className="flex items-center gap-4">
                        <Button variant="outline" size="sm">
                            Sign in
                        </Button>
                        <Button size="sm">Sign up</Button>
                        <ModeToggle />
                    </div>
                </div>
            </div>
        </nav>
    );
}
